const majors = [
  "Accounting",
  "Acting",
  "Actuarial Science",
  "American Studies",
  "Ancient Near Eastern Studies",
  "Animation",
  "Anthropology",
  "Anthropology",
  "Anthropology",
  "Applied Physics",
  "Arabic Language",
  "Art Education K-12",
  "Art History & Curatorial Studies",
  "Art",
  "Asian Studies",
  "Athletic Training",
  "Biochemistry",
  "Biodiversity & Conservation",
  "Bioinformatics",
  "Biological Science Education",
  "Biology",
  "Biophysics",
  "Business Management",
  "Chemical Engineering",
  "Chemistry Education",
  "Chemistry",
  "Chinese",
  "Civil Engineering",
  "Classical Studies",
  "Commercial Music",
  "Communication Disorders",
  "Communications",
  "Comparative Literature",
  "Computer Engineering",
  "Computer Science",
  "Construction and Facilities Management",
  "Cybersecurity",
  "Dance Education K-12",
  "Dance",
  "Design",
  "Dietetics",
  "Early Childhood Education",
  "Earth & Space Science Education",
  "Economics",
  "Editing and Publishing",
  "Electrical Engineering",
  "Elementary Education",
  "English Language",
  "English Teaching",
  "English",
  "Entrepreneurial Management",
  "Environmental Science",
  "European Studies",
  "Exercise & Wellness",
  "Exercise Science",
  "Experience Design and Management",
  "Family & Consumer Sciences Education",
  "Family History - Genealogy",
  "Family Life",
  "Finance",
  "Food Science",
  "French Studies",
  "French Teaching",
  "French",
  "General Studies",
  "Genetics, Genomics & Biotechnology",
  "Geography",
  "Geology",
  "German Studies",
  "German Teaching",
  "German",
  "Global Supply Chain Management",
  "Graphic Design",
  "History Teaching",
  "History",
  "Human Resource Management",
  "Illustration",
  "Industrial Design",
  "Information Systems",
  "Information Technology",
  "Interdisciplinary Humanities",
  "International Relations",
  "Italian Studies",
  "Italian",
  "Japanese",
  "Korean",
  "Landscape Management",
  "Latin American Studies",
  "Latin Teaching",
  "Linguistics",
  "Manufacturing Engineering",
  "Marketing",
  "Mathematics Education",
  "Mathematics: Applied and Computational Mathematics",
  "Mathematics",
  "Mechanical Engineering",
  "Media Arts Studies",
  "Medical Laboratory Science",
  "Microbiology",
  "Middle East Studies / Arabic",
  "Molecular Biology",
  "Music Composition",
  "Music Dance Theatre",
  "Music Education",
  "Music Performance",
  "Music",
  "Neuroscience",
  "Nursing",
  "Nutritional Science",
  "Philosophy",
  "Photography",
  "Physical Education Tchg/Coaching",
  "Physical Science Education",
  "Physics and Astronomy",
  "Physics Education",
  "Physics",
  "Physiology & Developmental Biology",
  "Political Science",
  "Portuguese Studies",
  "Portuguese",
  "Psychology",
  "Public Health",
  "Russian",
  "Social Science Teaching",
  "Sociology",
  "Spanish Studies",
  "Spanish Teaching",
  "Spanish Translation",
  "Spanish",
  "Special Education",
  "Statistics",
  "Strategic Management",
  "Technology & Engineering Studies",
  "Theatre Arts Education K-12",
  "Theatre Arts Studies",
  "Wildlife & Wildlands Conservation"
];

export default majors;
