const majors = [
  "Accounting",
  "Acting",
  "Actuarial Science",
  "American Studies",
  "Ancient Near Eastern Studies",
  "Animation",
  "Anthropology",
  "Anthropology",
  "Anthropology",
  "Applied Physics",
  "Arabic Language",
  "Art",
  "Art Education K-12",
  "Art History & Curatorial Studies",
  "Asian Studies",
  "Athletic Training",
  "Biochemistry",
  "Biodiversity & Conservation",
  "Bioinformatics",
  "Biological Science Education",
  "Biology",
  "Biophysics",
  "Business Management",
  "Chemical Engineering",
  "Chemistry",
  "Chemistry Education",
  "Chinese",
  "Civil Engineering",
  "Commercial Music",
  "Classical Studies",
  "Communications",
  "Communication Disorders",
  "Computer Engineering",
  "Comparative Literature",
  "Construction and Facilities Management",
  "Computer Science",
  "Dance",
  "Cybersecurity",
  "Design",
  "Dance Education K-12",
  "Early Childhood Education",
  "Dietetics",
  "Economics",
  "Earth & Space Science Education",
  "Electrical Engineering",
  "Editing and Publishing",
  "English",
  "Elementary Education",
  "English Teaching",
  "English Language",
  "Environmental Science",
  "Entrepreneurial Management",
  "Exercise & Wellness",
  "European Studies",
  "Experience Design and Management",
  "Exercise Science",
  "Family History - Genealogy",
  "Family & Consumer Sciences Education",
  "Finance",
  "Family Life",
  "French",
  "Food Science",
  "French Teaching",
  "French Studies",
  "Genetics, Genomics & Biotechnology",
  "General Studies",
  "Geology",
  "Geography",
  "German Teaching",
  "German Studies",
  "Global Supply Chain Management",
  "German",
  "History",
  "Graphic Design",
  "Human Resource Management",
  "History Teaching",
  "Industrial Design",
  "Illustration",
  "Information Technology",
  "Information Systems",
  "International Relations",
  "Interdisciplinary Humanities",
  "Italian Studies",
  "Italian",
  "Korean",
  "Japanese",
  "Latin American Studies",
  "Landscape Management",
  "Linguistics",
  "Latin Teaching",
  "Marketing",
  "Manufacturing Engineering",
  "Mathematics Education",
  "Mathematics",
  "Mechanical Engineering",
  "Mathematics: Applied and Computational Mathematics",
  "Medical Laboratory Science",
  "Media Arts Studies",
  "Middle East Studies / Arabic",
  "Microbiology",
  "Music",
  "Molecular Biology",
  "Music Dance Theatre",
  "Music Composition",
  "Music Performance",
  "Music Education",
  "Nursing",
  "Neuroscience",
  "Philosophy",
  "Nutritional Science",
  "Physical Education Tchg/Coaching",
  "Photography",
  "Physics",
  "Physical Science Education",
  "Physics Education",
  "Physics and Astronomy",
  "Political Science",
  "Physiology & Developmental Biology",
  "Portuguese Studies",
  "Portuguese",
  "Public Health",
  "Psychology",
  "Social Science Teaching",
  "Russian",
  "Spanish",
  "Sociology",
  "Spanish Teaching",
  "Spanish Studies",
  "Special Education",
  "Spanish Translation",
  "Strategic Management",
  "Statistics",
  "Theatre Arts Education K-12",
  "Technology & Engineering Studies",
  "Wildlife & Wildlands Conservation",
  "Theatre Arts Studies"
];

export default majors;
